services:
  server:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: mcgrath-server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=seminar
      - DB_PORT=27017
    depends_on:
      - mongodb

  client:
    build:
      context: ./Frontend
      dockerfile: Dockerfile

    container_name: mcgrath-client
    ports:
      - "80:80"
    depends_on:
      - server

  mongodb:
    image: mongo:latest
    container_name: mcgrath-db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    ports:
      - "27017:27017"

    volumes:
      - ./../mydata:/data/db

volumes: 
  mydata: